version: "3.9"
services:
  worker:
    build: .
    environment:
      - API_HASH=${API_HASH}
      - API_ID=${API_ID}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - AUTH_CHANNEL=${AUTH_CHANNEL}
      - OWNER_ID=${OWNER_ID}
